language: generic
sudo: required
services:
  docker
before_install:
  docker build -t rakeshkumardb/docker-react -f Dockerfile.dev .
script:
  docker run -e CI=true rakeshkumardb/docker-react npm run test


